### ISSUE TITLE
H5里输入框有个bug

### ISSUE THREAD

**Issue by yatoku** [xiaowang04821/fangwechat#1]
1.点击输入框的加号，然后底部栏的输入框变成了录音，再收缩回去也不会变回输入框。
2.H5不可以录音没有做条件编译

**Comment by xiaowang04821** [comment]
> 1.点击输入框的加号，然后底部栏的输入框变成了录音，再收缩回去也不会变回输入框。
> 2.H5不可以录音没有做条件编译

@yatoku 噢是的，这块没有针对H5做条件编译，因为某些原因这个项目很久没有维护了，得需要你自己去修改下源码啦:)

**Comment by yatoku** [comment]
> > 1.点击输入框的加号，然后底部栏的输入框变成了录音，再收缩回去也不会变回输入框。
> > 2.H5不可以录音没有做条件编译
> 
> @yatoku 噢是的，这块没有针对H5做条件编译，因为某些原因这个项目很久没有维护了，得需要你自己去修改下源码啦:)

好的，谢谢
